name: network_image_safe_provider
description: A Flutter library to handle NetworkImageProvider http. A placeholder will be displayed if there is a network error.
version: 1.0.0
homepage: https://micropp.net

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:


